Create two_cars_turn_right.py
KunSu/cmpe295 pull request #3
Opened 2020-07-28 07:34 UTC by zijianguan0204

2020-07-28 10:07 UTC, SungYinYang requested changes
What scenario model are you using?
Is it scenario model 8?
It should be one of the scenario model that list in Taylor's document.

2020-07-28 23:53 UTC, KunSu commented
> What scenario model are you using?
> Is it scenario model 8?
> It should be one of the scenario model that list in Taylor's document.
> 
> The variety of weather condition is not added.
> You could use two for loops like me to loop through weather condition.

GLTM.
No necessary to add the weather condition for all the scenarios. We might merge all weather-related script into one single template later on.

2020-07-28 23:53 UTC, KunSu approved these changes

2020-07-29 15:35 UTC, SungYinYang approved these changes
Check up scenario model then good.

2020-07-29 19:33 UTC, merged